server:
  port: 9091

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR


spring:
  application:
    name: address-manager
  datasource:
    url: jdbc:mysql://localhost:3306/addressdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    binders:
      system:
        enabled: false